bugfix for memory leak
FreeOpcUa/opcua-asyncio pull request #271
Opened 2020-08-24 10:22 UTC by JoeyFaulkner

implemented @oroulet comments on the other pull request, as much as i understood them https://github.com/JoeyFaulkner/opcua-asyncio/pull/3

2020-08-24 10:50 UTC, JoeyFaulkner commented
ok i think this error is out of my understanding https://travis-ci.org/github/FreeOpcUa/opcua-asyncio/jobs/720599077#L919

2020-08-24 13:24 UTC, swamper123 commented
This test "Run[s] an example OPC-UA server. By importing xml definition and using uawrite command line, it is even possible to expose real data using this server" within 2 seconds. After that, a SIGINT is send to the server and it has to shutdown in 2 seconds.

And there something is not working well...and I can't say exactly what. I would add a broad except block beside OSError and KeyboardInterrupt into this, perhaps you may catch an error with a better description.

(Perhaps these sleeps could be async as well, but I don't think that these are causing problems.)

2020-08-24 13:32 UTC, swamper123 requested changes

2020-08-24 13:32 UTC, swamper123 commented on asyncua/server/binary_server_asyncio.py
> +                logger.exception("Unexpected crash in BinaryServer._await_closing_tasks")
There is an empty line missing here.

2020-08-24 13:32 UTC, swamper123 commented on asyncua/server/binary_server_asyncio.py
> +    async def _await_closing_tasks(self):
If I understand this right, this method is just called at the start of a server? Or should it be call repeatadly?

2020-08-24 13:49 UTC, oroulet commented
Travis seemsto be down. What is the issue? It looks like master on my PC is broken too. I get a strange (RuntimeError: There is no current event loop....) No ideas where it comes from..

2020-08-24 13:57 UTC, swamper123 commented
![grafik](https://user-images.githubusercontent.com/24408657/91052928-6b32f680-e622-11ea-91c1-a2be17ee9362.png)

The process returns with 2 in the test.

2020-08-24 17:33 UTC, oroulet commented
travis is broken today. We need to wait...

2020-08-30 07:49 UTC, oroulet commented
see the other pull request

2020-08-30 07:49 UTC, closed without merging