DRAFT: initial use of dataclass
FreeOpcUa/opcua-asyncio pull request #420
Opened 2021-01-24 22:14 UTC by oroulet

2021-03-01 11:04 UTC, swamper123 requested changes
These are many changes on a realy deep level (well at least for me at the moment). 
We may should check out what the wanted behaviour with custom structs and similar should be (shall an ObjectID be added? Something else?), to avoid further problems.

2021-03-01 18:37 UTC, AndreasHeine commented on asyncua/common/structures.py
> +                            field.value = "field(default_factory=list)"
yes ^^

2021-03-01 18:38 UTC, AndreasHeine commented on asyncua/common/structures.py
> +                            field.value = "field(default_factory=list)"
_make_model --> generates code

2021-03-01 18:42 UTC, oroulet commented on asyncua/ua/ua_binary.py
> +    if vtype.value > 25:
since the line over return anyway the else is unnecessary. pylint complains about it and I agree it often leads to more readable code

2021-03-01 18:42 UTC, oroulet commented on asyncua/common/structures.py
> +                uatype = uatype
yes. that seems like a bug

2021-03-01 18:43 UTC, oroulet commented on asyncua/common/xmlexporter.py
> +            nodeid = ua.NodeId(nodeid.Identifier, NamespaceIndex=self._addr_idx_to_xml_idx[nodeid.NamespaceIndex])
correct. I should remove that copy. thanks

2021-03-01 18:53 UTC, AndreasHeine commented on schemas/generate_protocol_python.py
> +BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
why? its only for generation?

2021-03-01 19:09 UTC, oroulet commented on asyncua/ua/uatypes.py
> +            (uuid.UUID, [NodeIdType.Guid]),
that is common way to tell autoformater that I want one element per line

2021-03-01 19:10 UTC, oroulet commented on asyncua/ua/uatypes.py
> +        print(self.NodeIdType, self.NamespaceIndex, self.Identifier, other.NodeIdType, other.NamespaceIndex, other.Identifier)
that was an error . thanks

2021-03-01 19:10 UTC, oroulet commented on schemas/generate_model.py
> +    #from IPython import embed
removed

2021-03-01 19:11 UTC, oroulet commented on schemas/generate_protocol_python.py
> +BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
I think it will be next round. I have too many changes alreay

2021-03-02 06:36 UTC, swamper123 commented on asyncua/ua/ua_binary.py
> +    if vtype.value > 25:
Okay, in that case it is fine for me.

2021-03-02 07:05 UTC, swamper123 commented on schemas/generate_protocol_python.py
> +BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
@AndreasHeine I thought, that we want to replace the os module for path purposes.

2021-03-02 07:33 UTC, oroulet commented on schemas/generate_protocol_python.py
> +BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
we will do it. We can do it at next round when parsind xsd instead of bsd

2021-03-02 07:36 UTC, oroulet commented on schemas/generate_protocol_python.py
> +BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
it is not so important but when cleaning up things we can do it

2021-03-10 07:45 UTC, merged