Added StateMachine and FiniteStateMachine
FreeOpcUa/opcua-asyncio pull request #437
Opened 2021-02-05 20:54 UTC by AndreasHeine

2021-02-08 16:23 UTC, AndreasHeine commented on asyncua/common/statemachine.py
> +            self._transitiontime = datetime.datetime.utcnow() #will be overwritten from _write_transition()
initialize the statemachine (change to the initstate) is also a transition in my oppinion

2021-02-08 16:23 UTC, AndreasHeine commented on asyncua/common/statemachine.py
> +                await self._last_transition_number_node.write_value(transition.id, ua.VariantType.UInt32)
ty missed that one!

2021-02-08 16:23 UTC, AndreasHeine commented on asyncua/common/statemachine.py
> +            self.number = number
State and Transition Subclasses are for implementing StateVaraibleType and TransitionVariableType and yes you are right that they are optional, but i would not implement it without due to the fact that the opc ua way for implementing information in the addresspace is my focus and for that a name as browsename of the state node is better then childs with just ids... but i am open for discussions!

2021-02-08 16:23 UTC, AndreasHeine commented on asyncua/common/statemachine.py
> +        def __init__(self, name, id, number, node=None):
same comment like above!

2021-02-08 16:24 UTC, AndreasHeine commented
@swamper123 lets talk tomorow!

2021-02-09 14:01 UTC, swamper123 reviewed
Just found that one at the moment. Good job! 👍

2021-02-09 14:02 UTC, AndreasHeine commented on asyncua/common/statemachine.py
> +    async def change_state(self, state: State, transition: Transition=None, event_msg:str or ua.LocalizedText=None, severity: int=500):
ok good point

2021-02-09 14:05 UTC, swamper123 commented on asyncua/common/statemachine.py
> +    async def change_state(self, state: State, transition: Transition=None, event_msg:str or ua.LocalizedText=None, severity: int=500):
`from typing import Union`

2021-02-09 14:07 UTC, AndreasHeine commented on asyncua/common/statemachine.py
> +    async def change_state(self, state: State, transition: Transition=None, event_msg:str or ua.LocalizedText=None, severity: int=500):
...

2021-02-10 10:47 UTC, oroulet commented
so you want to merge?

2021-02-10 10:52 UTC, AndreasHeine commented
from my point maybe tomorrow! 
will improve some examples in the evening... just to show some more variance
@swamper123 are you done with the review?

2021-02-10 10:56 UTC, swamper123 commented
@AndreasHeine I will take a look on it again today and let you know.

2021-02-10 14:02 UTC, swamper123 requested changes
Beside some smaller style issues (there are more, maybe throw a linter on that and let the IDE reformat it), there are a few discussions points which should be solved.

2021-02-11 16:43 UTC, AndreasHeine commented
@oroulet ready to merge!

2021-02-11 18:12 UTC, merged