server read_attribute_value
FreeOpcUa/opcua-asyncio pull request #524
Opened 2021-03-30 20:50 UTC by AndreasHeine

![Unbenannt1](https://user-images.githubusercontent.com/56362817/113056338-f45b6e80-91ab-11eb-8332-8fe0a7baaee8.PNG)

2021-03-30 20:51 UTC, AndreasHeine commented on asyncua/server/internal_server.py
> +        await asyncio.sleep(0)
any better ideas?

2021-03-31 06:41 UTC, swamper123 approved these changes
I am a bit confused, why write_attribute_value is a coroutine, but read_attribute_value not ... Anyway I like the idea and can't see a problem at the moment with that, since this is server sided.

2021-03-31 07:05 UTC, oroulet commented
Is that an optimized server side read? like the write we currently have?
How much faster is it? or at least what kind of time consuming operation does it save?:
Also it should be async if it must be async (has some await somewhere inside) otherwise sync is fine

2021-03-31 07:11 UTC, oroulet commented on asyncua/server/internal_server.py
> +        await asyncio.sleep(0)
what is that line? It sould work withtout quite fine. Ans also that method does not need to be a coro

2021-03-31 07:56 UTC, AndreasHeine commented
it ment to be used as a serverside read without a nodeclassinstance so you save memmory and i like to use it for kind of gateway/aggregation pure serverside interaction in which storing just the nodeid is in my oppinion smarter then having thousands of nodeclass instances (with this change you can choose which way to go) 

i was kind of confused that addspace.read_attribute_value is not a coro... i would make it async and test if there are some sideeffects!

2021-04-04 17:21 UTC, oroulet requested changes

2021-04-05 08:53 UTC, oroulet commented
5 commits and manye discussion gor 5 simple lines ;-) but now it looks OK t least ;-)
obs btw: you should add test and maybe a line in one example because otherwise nobody is never going to find out it exist and without tests it will probably get broken at some points

2021-04-05 09:04 UTC, AndreasHeine commented
the overall result counts ;-)
adding tests!

2021-04-06 06:31 UTC, swamper123 commented on tests/test_server.py
> +    node = await server.get_objects_node().add_variable(0, "0:TestVar", 0, varianttype=ua.VariantType.Int64)
Since our tests all run on one Testserver, all nodes should be removed at the end of the test. Otherwise later tests may fail, because somebody wanted to add a "TestVar" Node as well.
Just add  `await opc.opc.delete_nodes([node])` at the end of the test.

2021-04-06 07:03 UTC, AndreasHeine commented on tests/test_server.py
> +    node = await server.get_objects_node().add_variable(0, "0:TestVar", 0, varianttype=ua.VariantType.Int64)
ok

2021-04-06 07:11 UTC, AndreasHeine commented
some how if i run test local they fail with file not found error (maybe something missing in my branch...):
![test](https://user-images.githubusercontent.com/56362817/113672337-e4fe8880-96b7-11eb-846a-5881b12e0b44.PNG)

but test_server.py is passing so it should be fine!

2021-04-06 07:33 UTC, oroulet commented on tests/test_server.py
> +    node = await server.get_objects_node().add_variable(0, "0:TestVar", 0, varianttype=ua.VariantType.Int64)
orgive them a name you know nobody else will use. 
Ideally these should be handled in pytest  fixtures... but it is not

2021-04-06 07:43 UTC, swamper123 commented
This is caused by #522 , happend to me as well.

2021-04-06 09:42 UTC, merged